language: java
jdk:
  - openjdk8
 
before_install:
  - echo $ENC_GPG_KEY | base64 --decode | gpg --import
  - echo $ENC_GPG_OWNER_TRUST | base64 --decode | gpg --import-ownertrust
  - gpg --list-keys

jobs:
  include:
    - stage: pr
      script: "mvn clean deploy"
      if: $TRAVIS_PULL_REQUEST" == 'true'
    - stage: ci
      script: "mvn clean deploy --settings settings.xml -B -Pdeploy"
      if: $TRAVIS_PULL_REQUEST" == 'false'
      on:
        branch: master
        tags: false
    - stage: release
      script: "mvn clean release:clean release:prepare release:perform --settings settings.xml -DSkipTests -B -Pdeploy"
      on:
        branch: master
        tags: true
        condition: $TRAVIS_TAG == "tag-new-release"

